language: node_js
node_js:
  - "5.1"
before_script:
  - npm install -g codacy-coverage coveralls
script:
  - npm run test:travis
after_script:
  - cat coverage/lcov.info | codacy-coverage
  - cat coverage/lcov.info | coveralls
before_deploy:
  - npm run build
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: pascal@openmrs.org
  api_key: $NPM_TOKEN
